apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-diff-tpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stable-diff-tpu
  template:
    metadata:
      labels:
        app: stable-diff-tpu
      annotations:
        tf-version.cloud-tpus.google.com: "2.6.0"
    spec:
      containers:
        - name: stable-diff-tpu
          image: gcr.io/stable-diffusion-368310/backend:v3
          resources:
            limits:
              # Request a single Preemptible v2-8 Cloud TPU device.
              cloud-tpus.google.com/preemptible-v2: 8
          ports:
            - containerPort: 8080
